baseURL = "https://liyangsong.github.io/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "Liyang Song"
copyright = "LiyangSong 2026"
# googleAnalytics = "UA-123-45"

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
#style = "perldoc"
tabWidth = 4

[params]
subtitle = "家園已在身後，世界儘在眼前"
favicon = "/favicon/favicon.ico"
avatar = "/img/avatar.png"
enableGitalk = false
enableGiscus = true

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = "abcdefghzd"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "Liyang Song" # will set 'og:site_name'
description = "家園已在身後，世界儘在眼前"  # will set 'og:description'

enableReadingTime = true

[params.gitalk]
owner = "user"
repo = "repo name"
client_id = "your client id"
client_secret = "your client secret"
[taxonomies]
tag = "tags"
category = "categories"
project = "projects"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
data_repo="LiyangSong/blog-comments"
data_repo_id="R_kgDOL-5fhg"
data_category="Announcements"
data_category_id="DIC_kwDOL-5fhs4Cfhvu"
data_mapping="pathname"
data_strict="0"
data_reactions_enabled="1"
data_emit_metadata="0"
data_input_position="top"
data_theme="preferred_color_scheme"
data_lang="en"
crossorigin="anonymous"

[[menu.main]]
url = "/posts/about"
name = "About 關於"
weight = 1
[[menu.main]]
url = "/posts/publications"
name = "Publications 出版物"
weight = 2
[[menu.main]]
url = "/projects"
name = "Projects 項目"
weight = 3
[[menu.main]]
url = "/posts"
name = "Posts 博文"
weight = 4
[[menu.main]]
url = "/files/Resume_Liyang_Song_012026.pdf"
name = "CV / Resume 履歷"
weight = 5
